### ISSUE TITLE
Can it sync with repo red hat 8 ? 

### ISSUE THREAD

**Issue by deaw0003** [dtmateojr/dtmrepo#16]
Can it sync with repo red hat 8 ?

**Comment by dtmateojr** [comment]
I haven’t tried. I can’t see why it wouldn’t you just need the product certs for RHEL8.

Have a read at Section VII item 4 of instructions.txt.

**Comment by deaw0003** [comment]
Yes I follow instruction Section VII item 4, I copy cert from rhel 8 server to my dtmrepo server (rhel7). It can sync repo baseos and appstream of rhel8.
But error occur while rhel8 server that need to upgrade patch via dtmrepo after use command "yum upgrade".
Below is link of image that show error.
https://imgur.com/DhA2Bs1

**Comment by dtmateojr** [comment]
I haven’t seen that error before. Looks like a yum bug. It should pick the latest version unless the dependency requires a specific version otherwise how would you install glibc for example? Gazillions of packages require glibc and I bet you have several versions of them in dtmrepo.
