### ISSUE TITLE
Help needed with creating config files for /etc/dtmrepo.conf.d/

### ISSUE THREAD

**Issue by ynodelman** [dtmateojr/dtmrepo#2]
Dear Sir,

I am new to Spacewalk and dtmrepo - we have RHEL5/6/7 Servers and I'm looking for the way to replicate repositories from redhat website and store them locally, I amd running Spacewalk 2.2 server on RHEL6 64-bit platform and was hoping to utilize this server for storing repos for all 3 RHEL releases:

as of now I created rhel7s file under 

[root@server dtmrepo.conf.d]# ls
rhel7s-x86_64.conf
[root@server dtmrepo.conf.d]# more rhel7s-x86_64.conf
[control]
arch = x86_64
keep = 2

[repos]
os = rhel-7-server-rpms
# when I execute "dtmrepo -augfv, I get the following output:

[root@server dtmrepo.conf.d]# dtmrepo -augfv
Synchronising distro rhel7s-x86_64 repo os.
Generating repodata for distro rhel7s-x86_64 repo os.
No files to process

Saving Primary metadata
Saving file lists metadata
Saving other metadata
Generating sqlite DBs
Starting other db creation: Fri Jan 16 11:15:04 2015
Ending other db creation: Fri Jan 16 11:15:04 2015
Starting filelists db creation: Fri Jan 16 11:15:04 2015
Ending filelists db creation: Fri Jan 16 11:15:04 2015
Starting primary db creation: Fri Jan 16 11:15:04 2015
Ending primary db creation: Fri Jan 16 11:15:04 2015
# Sqlite DBs complete

Please help, thank you.

**Comment by dtmateojr** [comment]
You need to initialise dtmrepo first. Please read the instructions.txt.

**Comment by ynodelman** [comment]
I did that. "dtmrepo -i" did not create any repo config files under "/etc/dtmrepo.conf.d/" folder - I am running RHEL6 64-bit OS and trying to get repo for RHEL7 64-bit OS.

Do I need to have RHEL7 64-bit server registered with redhat? On access.redhat.com website I don't see RHEL7 channel listed as one of my choices.

**Comment by dtmateojr** [comment]
You will have to manually create the el7 repo file in /etc/yum.repos.d. You could just use "sed" to create a new one from the el6 repo that got generated by subscription-manager. Or if you have an existing el7 server that is subscribed, get the redhat.repo and copy it to your dtmrepo server but make sure that you disable all the repos otherwise the next time you run "yum update" on your dtmrepo server it will update it into el7.

**Comment by ynodelman** [comment]
Hi,

I was able successfully download rhel7 repos from redhat utilizing your script - thank you. Now I have a dilemma trying to generate errata for rhel7 under spacewalk 2.2 - script "rhn-clone-errata.py" does not work for rhel-x86_64-server-7 channel, any idea how I can overcome this problem?

Sorry and thank you for your help

**Comment by dtmateojr** [comment]
Sorry, I didn't quite understand the problem. Could you please explain what you are trying to do.

**Comment by ynodelman** [comment]
Hi,

At this point my problem is unrelated to repo syncs. I am looking for the way to replicate erratas for RHEL7 channel from Redhat to my local Spacewalk server.
